backend/core/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('dashboard.urls')),
    path('ventes/', include('ventes.urls')),
    path('produit/', include('produits.urls')),
    path('batiments/', include('batiments.urls')),
    path('clients/', include('clients.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/produits/forms.py
# forms.py
from django import forms
from batiments.models import Batiment
from .models import Race, Lot, Aliment, Traitement
from .rapport import JournalisationQuotidienne, Alimentation, RamassageOeufs, HistoriqueTraitement, Provision

class RaceForm(forms.ModelForm):
    nom = forms.CharField(
        label="Nom",
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'})
    )
    description = forms.CharField(
        label="Description",
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'})
    )
    photo = forms.ImageField(
        label="Photo",
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Race
        fields = ['nom', 'description', 'photo']

class BandeForm(forms.ModelForm):
    nom = forms.CharField(
        label="Nom",
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'})
    )
    race = forms.ModelChoiceField(
        queryset=Race.objects.all(),
        label="Race",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    batiment = forms.ModelChoiceField(
        queryset=Batiment.objects.all(),
        label="Bâtiment",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    date_arrivee = forms.DateField(
        label="Date d'arrivée",
        widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Date d\'arrivée', 'type': 'date'})
    )
    age_arrivee = forms.IntegerField(
        label="Âge à l'arrivée",
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Âge à l\'arrivée'})
    )
    nombre_arrivee = forms.IntegerField(
        label="Nombre à l'arrivée",
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Nombre à l\'arrivée'})
    )

    nombre_deces = forms.IntegerField(
        label="Nombre de décès",
        initial=0,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de décès'})
    )
    nombre_malade = forms.IntegerField(
        label="Nombre de malades",
        initial=0,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de malades'})
    )
    traitement_imminent = forms.IntegerField(
        label="Traitement imminent",
        initial=0,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Traitement imminent'})
    )
    details = forms.CharField(
        label="Détails",
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Détails'})
    )

    class Meta:
        model = Lot
        fields = [
            'nom', 'race', 'batiment', 'date_arrivee', 'age_arrivee',
            'nombre_arrivee', 'nombre_deces',
            'nombre_malade', 'traitement_imminent', 'details'
        ]

class BandeUpdateForm(forms.ModelForm):
    nom = forms.CharField(
        label="Nom",
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'})
    )
    race = forms.ModelChoiceField(
        queryset=Race.objects.all(),
        label="Race",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    batiment = forms.ModelChoiceField(
        queryset=Batiment.objects.all(),
        label="Bâtiment",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    date_arrivee = forms.DateField(
        label="Date d'arrivée",
        widget=forms.DateInput(attrs={'class': 'form-control'})
    )
    age_arrivee = forms.IntegerField(
        label="Âge à l'arrivée",
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Âge à l\'arrivée'})
    )
    nombre_arrivee = forms.IntegerField(
        label="Nombre à l'arrivée",
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Nombre à l\'arrivée'})
    )

    nombre_deces = forms.IntegerField(
        label="Nombre de décès",
        initial=0,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de décès'})
    )
    nombre_malade = forms.IntegerField(
        label="Nombre de malades",
        initial=0,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de malades'})
    )
    traitement_imminent = forms.IntegerField(
        label="Traitement imminent",
        initial=0,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Traitement imminent'})
    )
    details = forms.CharField(
        label="Détails",
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Détails'})
    )

    class Meta:
        model = Lot
        fields = [
            'nom', 'race', 'batiment', 'date_arrivee', 'age_arrivee',
            'nombre_arrivee', 'nombre_deces',
            'nombre_malade', 'traitement_imminent', 'details'
        ]


class AlimentForm(forms.ModelForm):
    UNITE_CHOICES = (
        ('kg', 'Kilogrammes'),
        ('g', 'Grammes'),
        ('L', 'Litres'),
        ('ml', 'Millilitres'),
        ('unité', 'Unité'),
    )

    nom = forms.CharField(
        label="Nom",
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'})
    )
    description = forms.CharField(
        label="Description",
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'})
    )
    prix_unitaire = forms.DecimalField(
        label="Prix unitaire",
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Prix unitaire'})
    )
    unite_mesure = forms.ChoiceField(
        label="Unité de mesure",
        choices=UNITE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Aliment
        fields = ['nom', 'description', 'prix_unitaire', 'unite_mesure']

class TraitementForm(forms.ModelForm):
    nom = forms.CharField(
        label="Nom",
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'})
    )
    description = forms.CharField(
        label="Description",
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'})
    )
    duree_jours = forms.IntegerField(
        label="Durée (jours)",
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Durée (jours)'})
    )

    class Meta:
        model = Traitement
        fields = ['nom', 'description', 'duree_jours']
#-------------------------------------operations---------------------------------------------------------------------
class JournalisationQuotidienneForm(forms.ModelForm):
    class Meta:
        model = JournalisationQuotidienne
        exclude = ['lot']  # Exclure le champ lot des champs affichés

    def __init__(self, *args, **kwargs):
        lot_id = kwargs.pop('lot_id', None)  # Récupérer lot_id depuis les arguments kwargs
        super().__init__(*args, **kwargs)
        if lot_id:
            self.instance.lot_id = lot_id  # Assigner lot_id à l'instance du formulaire
        self.fields['date_journalisation'].widget.attrs.update({
            'class': 'form-control',  # Ajout de la classe form-control
            'type': 'date'  # Définition du type de champ à date
        })
        self.fields['nombre_vivants'].widget.attrs['class'] = 'form-control'
        self.fields['nombre_deces'].widget.attrs['class'] = 'form-control'
        self.fields['nombre_malades'].widget.attrs['class'] = 'form-control'
        self.fields['autres_informations'].widget.attrs['class'] = 'form-control'


class AlimentationForm(forms.ModelForm):
    class Meta:
        model = Alimentation
        exclude = ['lot']

    def __init__(self, *args, **kwargs):
        lot_id = kwargs.pop('lot_id', None)
        super().__init__(*args, **kwargs)
        if lot_id:
            self.instance.lot_id = lot_id
        self.fields['date_alimentation'].widget.attrs.update({
            'class': 'form-control',
            'type': 'date',
            'placeholder': 'Sélectionnez une date',
        })
        self.fields['quantite'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Entrez la quantité (kg)',
        })
        self.fields['type_aliment'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Entrez le type d\'aliment',
        })
        self.fields['commentaire'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Entrez un commentaire (optionnel)',
        })


class RamassageOeufsForm(forms.ModelForm):
    class Meta:
        model = RamassageOeufs
        exclude = ['lot']  # Exclure le champ lot des champs affichés

    def __init__(self, *args, **kwargs):
        lot_id = kwargs.pop('lot_id', None)  # Récupérer lot_id depuis les arguments kwargs
        super().__init__(*args, **kwargs)
        if lot_id:
            self.instance.lot_id = lot_id  # Assigner lot_id à l'instance du formulaire
        self.fields['date_ramassage'].widget.attrs['class'] = 'form-control'
        self.fields['date_ramassage'].widget.attrs['type'] = 'date'
        self.fields['quantite_premier_ramassage'].widget.attrs['class'] = 'form-control'
        self.fields['quantite_deuxieme_ramassage'].widget.attrs['class'] = 'form-control'
        self.fields['quantite_troisieme_ramassage'].widget.attrs['class'] = 'form-control'
        self.fields['quantite_quatrieme_ramassage'].widget.attrs['class'] = 'form-control'
        self.fields['commentaire'].widget.attrs['class'] = 'form-control'

class HistoriqueTraitementForm(forms.ModelForm):
    class Meta:
        model = HistoriqueTraitement
        exclude = ['lot']  # Exclure le champ lot des champs affichés

    def __init__(self, *args, **kwargs):

backend/templates/journalisation/journalisation_form.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="row">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    </div>
    <div class="col-lg-6">
        <div class="card border-0 shadow mb-4">
            <div class="card-body">
                <h2 class="h5 mb-4">Modifier une journalisation</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-primary">Ajouter</button>
                    <a href="{% url 'race-list' %}" class="btn btn-secondary">Liste</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

backend/templates/journalisation/journalisation_list.html
{% extends "layouts/base.html" %}

{% block content %}

<div class="row">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
        <div>
            <button class="btn btn-secondary d-inline-flex align-items-center me-2" data-bs-toggle="modal" data-bs-target="#createJournalisationModal">
                <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                Créer
            </button>
        </div>
        <div class="dropdown">
            {% include "heas.html" %}
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card border-0 shadow mb-4">
            <div class="card-body">
                <h2 class="h5 mb-4">Liste des journalisations</h2>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Lot</th>
                                <th>Date de Journalisation</th>
                                <th>Nombre de Vivants</th>
                                <th>Nombre de Décès</th>
                                <th>Nombre de Malades</th>
                                <th>Autres Informations</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for journalisation in journalisations %}
                            <tr>
                                <td>{{ journalisation.lot.nom }}</td>
                                <td>{{ journalisation.date_journalisation }}</td>
                                <td>{{ journalisation.nombre_vivants }}</td>
                                <td>{{ journalisation.nombre_deces }}</td>
                                <td>{{ journalisation.nombre_malades }}</td>
                                <td>{{ journalisation.autres_informations }}</td>
                                <td>
                                    <!-- Boutons d'action -->
                                    <a class="btn btn-sm btn-info me-1" href="{% url 'journalisation-update' journalisation.id %}">
                                        Modifier
                                    </a>
                                    <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteJournalisationModal{{ journalisation.id }}">
                                        Supprimer
                                    </button>
                                    <!-- Modal de suppression pour chaque journalisation -->
                                    <div class="modal fade" id="deleteJournalisationModal{{ journalisation.id }}" tabindex="-1" aria-labelledby="deleteJournalisationModalLabel{{ journalisation.id }}" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteJournalisationModalLabel{{ journalisation.id }}">Supprimer Journalisation</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Êtes-vous sûr de vouloir supprimer cette journalisation ?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                                                    <form method="post" action="{% url 'journalisation-delete' journalisation.id %}" style="display: inline;">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="journalisation_id" value="{{ journalisation.id }}">
                                                        <button type="submit" name="delete_journalisation" class="btn btn-sm btn-danger">Supprimer</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="7">Aucune journalisation trouvée.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal de création de journalisation -->
<div class="modal fade" id="createJournalisationModal" tabindex="-1" aria-labelledby="createJournalisationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createJournalisationModalLabel">Créer une nouvelle journalisation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="mb-3">
                        <label for="id_date_journalisation">Date de Journalisation:</label>
                        <input type="date" class="form-control" id="id_date_journalisation" name="date_journalisation" value="{{ form.date_journalisation.value|date:'Y-m-d' }}" required>
                        <!-- Affichage des erreurs -->
                        {% if create_form.date_journalisation.errors %}
                            {% for error in create_form.date_journalisation.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="id_nombre_vivants">Nombre de Vivants:</label>
                        {{ create_form.nombre_vivants }}
                        <!-- Affichage des erreurs -->
                        {% if create_form.nombre_vivants.errors %}
                            {% for error in create_form.nombre_vivants.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="id_nombre_deces">Nombre de Décès:</label>
                        {{ create_form.nombre_deces }}
                        <!-- Affichage des erreurs -->
                        {% if create_form.nombre_deces.errors %}
                            {% for error in create_form.nombre_deces.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="id_nombre_malades">Nombre de Malades:</label>
                        {{ create_form.nombre_malades }}
                        <!-- Affichage des erreurs -->
                        {% if create_form.nombre_malades.errors %}
                            {% for error in create_form.nombre_malades.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="id_autres_informations">Autres Informations:</label>
                        {{ create_form.autres_informations }}
                        <!-- Affichage des erreurs -->
                        {% if create_form.autres_informations.errors %}
                            {% for error in create_form.autres_informations.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <button type="submit" name="create_journalisation" class="btn btn-primary">Créer</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}